### PR TITLE
Issue #675 default title for images

### PR DESCRIPTION
**Pull request by PaulSchroeder**
refactored tile viewer, harmonized image and text tiles in a single component
issue #675

### CODE REVIEW

**Comment by simon-clematide** [comment]
As I am still not dockerified enough I cannot look into right now. But I trust that a more unified presentation is beneficial:-) Thanks a lot, SImon

**Comment by danieleguido** [comment]
preview of this PR:
Screenshot 2020-02-05 at 09 32 39

current preview:
Screenshot 2020-02-05 at 09 36 05

**Comment by PaulSchroeder** [comment]
Thanks @danieleguido for pointing this out! I was in the process of cleaning up duplicate style definitions in multiple components.
I wasn’t aware that the tile class affected list results ...

**Comment by danieleguido** [comment]
Close as it has been fixed in another PR

**Pull request closed without merging**
